"""GitHub campaign publication and exact-candidate workflow."""

from foundry_opt.github_workflow.errors import (
    CampaignPublicationError,
    CandidatePublicationError,
    GitHubPermissionDeniedError,
    GitHubWorkflowError,
    PatchApplicationError,
    PatchTraversalError,
    PatchTreeMismatchError,
)
from foundry_opt.github_workflow.models import (
    AppliedPatch,
    ArtifactReference,
    ArtifactInspection,
    CampaignPublication,
    CampaignPublicationRequest,
    CommitBlob,
    CommitInspection,
    CandidateApplicationResult,
    CandidateApplicationStatus,
    CandidateApplicationRequest,
    CandidateIssuePublication,
    GitHubCapabilities,
    GitHubPermissionReport,
    ExactPatchRequest,
    IssueReference,
    PullRequestReference,
    RedactionProvenance,
    RepositoryState,
    WorkflowFailure,
)
from foundry_opt.github_workflow.candidate import verify_and_apply_candidate
from foundry_opt.github_workflow.publication import publish_campaign

__all__ = [
    "AppliedPatch",
    "ArtifactReference",
    "ArtifactInspection",
    "CampaignPublication",
    "CampaignPublicationError",
    "CampaignPublicationRequest",
    "CommitBlob",
    "CommitInspection",
    "CandidateApplicationRequest",
    "CandidateApplicationResult",
    "CandidateApplicationStatus",
    "CandidateIssuePublication",
    "CandidatePublicationError",
    "ExactPatchRequest",
    "GitHubCapabilities",
    "GitHubPermissionDeniedError",
    "GitHubPermissionReport",
    "GitHubWorkflowError",
    "IssueReference",
    "PatchApplicationError",
    "PatchTraversalError",
    "PatchTreeMismatchError",
    "PullRequestReference",
    "RedactionProvenance",
    "RepositoryState",
    "WorkflowFailure",
    "publish_campaign",
    "verify_and_apply_candidate",
]
