from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from foundry_opt.onboarding.generation import (
    generate_change_contents,
    validate_generation_inputs,
    validate_request_inputs,
)
from foundry_opt.onboarding.interfaces import (
    DiscoveryGateway,
    DraftProbe,
    ChangeSetWriter,
    GitHubVariableConfigurer,
    OnboardingPublisher,
    OidcVerifier,
)
from foundry_opt.onboarding.models import (
    ChangeStatus,
    DraftPullRequest,
    OnboardingChange,
    OnboardingRequest,
    OnboardingResult,
    OnboardingStatus,
)
from foundry_opt.onboarding.variables import (
    UnavailableGitHubVariableConfigurer,
)
from foundry_opt.preflight.redaction import redact
from foundry_opt.onboarding.repository import (
    ChangeSetConflictError,
    ChangeSetError,
    ChangeSetWriteError,
    OnboardingPublishError,
    SafeChangeSetWriter,
    UnavailableOnboardingPublisher,
)


@dataclass(frozen=True)
class OnboardingDependencies:
    discovery: DiscoveryGateway
    oidc: OidcVerifier
    draft_probe: DraftProbe
    publisher: OnboardingPublisher = field(
        default_factory=UnavailableOnboardingPublisher
    )
    change_writer: ChangeSetWriter = field(
        default_factory=SafeChangeSetWriter
    )
    variables: GitHubVariableConfigurer = field(
        default_factory=UnavailableGitHubVariableConfigurer
    )


def run_onboarding(
    request: OnboardingRequest,
    dependencies: OnboardingDependencies,
) -> OnboardingResult:
    draft_pr = DraftPullRequest(
        title="Configure Foundry optimizer onboarding",
        body=(
            "Draft onboarding change set generated by `foundry-opt init`. "
            "Review discovered targets, validation commands, metric policies, "
            "OIDC trust, and offline checks before merging."
        ),
    )
    request_blockers = validate_request_inputs(request)
    if request_blockers:
        return OnboardingResult(
            status=OnboardingStatus.BLOCKED,
            changes=(),
            draft_pull_request=draft_pr,
            blockers=request_blockers,
        )
    try:
        discovery = dependencies.discovery.discover(request)
    except Exception as error:
        return _blocked(
            draft_pr,
            f"Discovery failed: {_safe_error(error)}",
        )

    guard_blockers = _repository_guard_blockers(discovery)
    input_blockers = validate_generation_inputs(request, discovery)
    if guard_blockers or input_blockers:
        return OnboardingResult(
            status=OnboardingStatus.BLOCKED,
            changes=(),
            draft_pull_request=draft_pr,
            discovery=discovery,
            blockers=(*guard_blockers, *input_blockers),
        )

    try:
        oidc = dependencies.oidc.verify(request, discovery)
    except Exception as error:
        return _blocked(
            draft_pr,
            f"OIDC verification failed: {_safe_error(error)}",
            discovery=discovery,
        )
    if not oidc.verified or oidc.repository_id != discovery.repository_id:
        return _blocked(
            draft_pr,
            "The exact immutable repository-ID OIDC trust was not verified.",
            discovery=discovery,
            oidc=oidc,
        )

    try:
        contents = generate_change_contents(
            request,
            discovery,
            oidc_subject=oidc.subject,
        )
    except Exception as error:
        return _blocked(
            draft_pr,
            f"Change-set generation failed: {_safe_error(error)}",
            discovery=discovery,
            oidc=oidc,
        )
    try:
        planned_changes = dependencies.change_writer.prevalidate(
            request.repository_root,
            contents,
        )
    except ChangeSetConflictError as error:
        return _conflict_result(
            draft_pr,
            contents,
            error,
            discovery=discovery,
            oidc=oidc,
        )
    except ChangeSetError as error:
        return _blocked(
            draft_pr,
            f"Generated change set is unsafe: {_safe_error(error)}",
            discovery=discovery,
            oidc=oidc,
        )
    if planned_changes and all(
        change.status is ChangeStatus.UNCHANGED
        for change in planned_changes
    ):
        variable_changes = ()
        if request.set_github_variables:
            try:
                variable_changes = dependencies.variables.configure(
                    request,
                    discovery,
                )
            except RuntimeError as error:
                return OnboardingResult(
                    status=OnboardingStatus.PARTIAL,
                    changes=planned_changes,
                    draft_pull_request=draft_pr,
                    discovery=discovery,
                    oidc=oidc,
                    blockers=(
                        "GitHub variable configuration failed: "
                        f"{_safe_error(error)}",
                    ),
                )
        return OnboardingResult(
            status=OnboardingStatus.READY,
            changes=planned_changes,
            draft_pull_request=draft_pr,
            discovery=discovery,
            oidc=oidc,
            variable_changes=variable_changes,
            guidance=(
                "Generated onboarding files are already current.",
            ),
        )
    foundry_agent = next(
        agent
        for agent in discovery.foundry_agents
        if agent.name == request.target_name
    )
    local_agent = next(
        agent
        for agent in discovery.python_agents
        if agent.name == request.target_name
    )
    try:
        probe = dependencies.draft_probe.probe(
            request,
            foundry_agent,
            local_agent,
        )
    except Exception as error:
        return _blocked(
            draft_pr,
            "Draft semantics probe blocked onboarding: "
            f"{_safe_error(error)}",
            discovery=discovery,
            oidc=oidc,
            changes=planned_changes,
        )
    if (
        probe.agent_name != foundry_agent.name
        or not probe.version.startswith("draft-")
    ):
        return _blocked(
            draft_pr,
            "Draft semantics probe did not return a draft-* version; "
            "nothing was deleted.",
            discovery=discovery,
            oidc=oidc,
            draft_probe=probe,
            changes=planned_changes,
        )
    try:
        dependencies.draft_probe.delete_probe(
            probe.agent_name,
            probe.version,
        )
    except Exception as error:
        return _blocked(
            draft_pr,
            f"Draft probe cleanup failed: {_safe_error(error)}",
            discovery=discovery,
            oidc=oidc,
            draft_probe=probe,
            changes=planned_changes,
        )

    try:
        changes = dependencies.change_writer.write(
            request.repository_root,
            contents,
        )
    except ChangeSetConflictError as error:
        return _conflict_result(
            draft_pr,
            contents,
            error,
            discovery=discovery,
            oidc=oidc,
            draft_probe=probe,
        )
    except ChangeSetWriteError as error:
        if error.residual_paths or error.cleanup_errors:
            return OnboardingResult(
                status=OnboardingStatus.PARTIAL,
                changes=planned_changes,
                draft_pull_request=draft_pr,
                discovery=discovery,
                oidc=oidc,
                draft_probe=probe,
                blockers=(_safe_error(error),),
                residual_state=(
                    *(
                        path.as_posix()
                        for path in error.residual_paths
                    ),
                    *error.cleanup_errors,
                ),
            )
        return _blocked(
            draft_pr,
            _safe_error(error),
            discovery=discovery,
            oidc=oidc,
            draft_probe=probe,
            changes=planned_changes,
        )
    except ChangeSetError as error:
        return _blocked(
            draft_pr,
            _safe_error(error),
            discovery=discovery,
            oidc=oidc,
            draft_probe=probe,
            changes=planned_changes,
        )
    try:
        publication = dependencies.publisher.publish(
            request,
            discovery,
            changes,
            draft_pr,
        )
    except OnboardingPublishError as error:
        if error.residual_state:
            return OnboardingResult(
                status=OnboardingStatus.PARTIAL,
                changes=changes,
                draft_pull_request=draft_pr,
                discovery=discovery,
                oidc=oidc,
                draft_probe=probe,
                blockers=(
                    "Draft pull request publication failed during "
                    f"{error.phase}: {_safe_error(error)}",
                ),
                residual_state=error.residual_state,
            )
        return _blocked(
            draft_pr,
            "Draft pull request publication failed during "
            f"{error.phase}: {_safe_error(error)}",
            discovery=discovery,
            oidc=oidc,
            draft_probe=probe,
            changes=changes,
        )
    except RuntimeError as error:
        return _blocked(
            draft_pr,
            f"Draft pull request publication failed: {_safe_error(error)}",
            discovery=discovery,
            oidc=oidc,
            draft_probe=probe,
            changes=changes,
        )
    variable_changes = ()
    if request.set_github_variables:
        try:
            variable_changes = dependencies.variables.configure(
                request,
                discovery,
            )
        except RuntimeError as error:
            return OnboardingResult(
                status=OnboardingStatus.PARTIAL,
                changes=changes,
                draft_pull_request=draft_pr,
                discovery=discovery,
                oidc=oidc,
                draft_probe=probe,
                published_pull_request=publication,
                blockers=(
                    "GitHub variable configuration failed: "
                    f"{_safe_error(error)}",
                ),
                residual_state=(
                    f"Draft onboarding PR: {publication.url}",
                ),
            )
    return OnboardingResult(
        status=OnboardingStatus.READY,
        changes=changes,
        draft_pull_request=draft_pr,
        discovery=discovery,
        oidc=oidc,
        draft_probe=probe,
        published_pull_request=publication,
        variable_changes=variable_changes,
        guidance=(
            *(
                (
                    "Repository-level GitHub Agents variables were configured.",
                )
                if request.set_github_variables
                else (
                    "Create non-secret GitHub Agents variables "
                    "AZURE_TENANT_ID, AZURE_CLIENT_ID, and "
                    "AZURE_SUBSCRIPTION_ID.",
                )
            ),
            *(
                (
                    "The Actions deployment environment "
                    f"{request.mirror_actions_environment} received the "
                    "separate AZURE_DEPLOYMENT_CLIENT_ID variable.",
                )
                if request.mirror_actions_environment is not None
                else (
                    "Create AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID, and "
                    "AZURE_DEPLOYMENT_CLIENT_ID in the Actions environment "
                    f"{request.environment_name}.",
                )
            ),
            "Azure OIDC does not require GitHub Agents or Actions secrets.",
            "Create the generated [Optimize] issue to start a campaign; "
            "workflow dispatch is retry-only.",
            f"Draft onboarding pull request created: {publication.url}",
        ),
    )


def _repository_guard_blockers(discovery) -> tuple[str, ...]:
    blockers: list[str] = []
    if discovery.current_branch != discovery.default_branch:
        blockers.append("Onboarding must run on the default branch.")
    if not discovery.clean:
        blockers.append("Onboarding requires a clean worktree.")
    if not discovery.authenticated_login:
        blockers.append("A locally authenticated GitHub user is required.")
    if discovery.viewer_permission.casefold() != "admin":
        blockers.append("The authenticated GitHub user must have ADMIN permission.")
    return tuple(blockers)


def _blocked(
    draft_pr: DraftPullRequest,
    blocker: str,
    changes: tuple[OnboardingChange, ...] = (),
    **values,
) -> OnboardingResult:
    return OnboardingResult(
        status=OnboardingStatus.BLOCKED,
        changes=changes,
        draft_pull_request=draft_pr,
        blockers=(blocker,),
        **values,
    )


def _conflict_result(
    draft_pr: DraftPullRequest,
    contents: dict[Path, str],
    error: ChangeSetConflictError,
    **values,
) -> OnboardingResult:
    conflict_set = set(error.paths)
    paths = (*contents, *(path for path in error.paths if path not in contents))
    return OnboardingResult(
        status=OnboardingStatus.CONFLICT,
        changes=tuple(
            OnboardingChange(
                path=path,
                content=contents.get(path, ""),
                status=(
                    ChangeStatus.CONFLICT
                    if path in conflict_set
                    else ChangeStatus.PLANNED
                ),
                detail=(
                    "Existing path was preserved."
                    if path in conflict_set
                    else None
                ),
            )
            for path in paths
        ),
        draft_pull_request=draft_pr,
        blockers=tuple(
            f"Existing path was not overwritten: {path.as_posix()}"
            for path in error.paths
        ),
        **values,
    )


def _safe_error(error: Exception) -> str:
    return redact(str(error)) or error.__class__.__name__
