from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from foundry_opt.onboarding.generation import (
    generate_change_contents,
    validate_generation_inputs,
    validate_request_inputs,
)
from foundry_opt.onboarding.interfaces import (
    DiscoveryGateway,
    DraftProbe,
    OidcVerifier,
)
from foundry_opt.onboarding.models import (
    ChangeStatus,
    DraftPullRequest,
    OnboardingChange,
    OnboardingRequest,
    OnboardingResult,
    OnboardingStatus,
)
from foundry_opt.preflight.redaction import redact


@dataclass(frozen=True)
class OnboardingDependencies:
    discovery: DiscoveryGateway
    oidc: OidcVerifier
    draft_probe: DraftProbe


def run_onboarding(
    request: OnboardingRequest,
    dependencies: OnboardingDependencies,
) -> OnboardingResult:
    draft_pr = DraftPullRequest(
        title="Configure Foundry optimizer onboarding",
        body=(
            "Draft onboarding change set generated by `foundry-opt init`. "
            "Review discovered targets, validation commands, metric policies, "
            "OIDC trust, and offline checks before merging."
        ),
    )
    request_blockers = validate_request_inputs(request)
    if request_blockers:
        return OnboardingResult(
            status=OnboardingStatus.BLOCKED,
            changes=(),
            draft_pull_request=draft_pr,
            blockers=request_blockers,
        )
    try:
        discovery = dependencies.discovery.discover(request)
    except Exception as error:
        return _blocked(
            draft_pr,
            f"Discovery failed: {_safe_error(error)}",
        )

    guard_blockers = _repository_guard_blockers(discovery)
    input_blockers = validate_generation_inputs(discovery)
    if guard_blockers or input_blockers:
        return OnboardingResult(
            status=OnboardingStatus.BLOCKED,
            changes=(),
            draft_pull_request=draft_pr,
            discovery=discovery,
            blockers=(*guard_blockers, *input_blockers),
        )

    try:
        oidc = dependencies.oidc.verify(request, discovery)
    except Exception as error:
        return _blocked(
            draft_pr,
            f"OIDC verification failed: {_safe_error(error)}",
            discovery=discovery,
        )
    if not oidc.verified or oidc.repository_id != discovery.repository_id:
        return _blocked(
            draft_pr,
            "The exact immutable repository-ID OIDC trust was not verified.",
            discovery=discovery,
            oidc=oidc,
        )

    try:
        contents = generate_change_contents(
            request,
            discovery,
            oidc_subject=oidc.subject,
        )
    except Exception as error:
        return _blocked(
            draft_pr,
            f"Change-set generation failed: {_safe_error(error)}",
            discovery=discovery,
            oidc=oidc,
        )
    planned_changes = tuple(
        OnboardingChange(
            path=path,
            content=content,
            status=ChangeStatus.PLANNED,
        )
        for path, content in contents.items()
    )
    conflicts = tuple(
        change.path
        for change in planned_changes
        if (request.repository_root / change.path).exists()
    )
    if conflicts:
        conflict_set = set(conflicts)
        return OnboardingResult(
            status=OnboardingStatus.CONFLICT,
            changes=tuple(
                OnboardingChange(
                    path=change.path,
                    content=change.content,
                    status=(
                        ChangeStatus.CONFLICT
                        if change.path in conflict_set
                        else ChangeStatus.PLANNED
                    ),
                    detail=(
                        "Existing path was preserved."
                        if change.path in conflict_set
                        else None
                    ),
                )
                for change in planned_changes
            ),
            draft_pull_request=draft_pr,
            discovery=discovery,
            oidc=oidc,
            blockers=tuple(
                f"Existing path was not overwritten: {path.as_posix()}"
                for path in conflicts
            ),
        )
    foundry_agent = next(
        (
            agent
            for agent in discovery.foundry_agents
            if agent.name == request.target_name
        ),
        discovery.foundry_agents[0],
    )
    try:
        probe = dependencies.draft_probe.probe(request, foundry_agent)
    except Exception as error:
        return _blocked(
            draft_pr,
            "Draft semantics probe blocked onboarding: "
            f"{_safe_error(error)}",
            discovery=discovery,
            oidc=oidc,
            changes=planned_changes,
        )
    if (
        probe.agent_name != foundry_agent.name
        or not probe.version.startswith("draft-")
    ):
        return _blocked(
            draft_pr,
            "Draft semantics probe did not return a draft-* version; "
            "nothing was deleted.",
            discovery=discovery,
            oidc=oidc,
            draft_probe=probe,
            changes=planned_changes,
        )
    try:
        dependencies.draft_probe.delete_probe(
            probe.agent_name,
            probe.version,
        )
    except Exception as error:
        return _blocked(
            draft_pr,
            f"Draft probe cleanup failed: {_safe_error(error)}",
            discovery=discovery,
            oidc=oidc,
            draft_probe=probe,
            changes=planned_changes,
        )

    changes = tuple(
        _write_new_file(request.repository_root, path, content)
        for path, content in contents.items()
    )
    status = (
        OnboardingStatus.CONFLICT
        if any(change.status is ChangeStatus.CONFLICT for change in changes)
        else OnboardingStatus.READY
    )
    blockers = tuple(
        f"Existing path was not overwritten: {change.path.as_posix()}"
        for change in changes
        if change.status is ChangeStatus.CONFLICT
    )
    return OnboardingResult(
        status=status,
        changes=changes,
        draft_pull_request=draft_pr,
        discovery=discovery,
        oidc=oidc,
        draft_probe=probe,
        blockers=blockers,
        guidance=(
            "Create non-secret GitHub Actions variables AZURE_TENANT_ID, "
            "AZURE_CLIENT_ID, and AZURE_SUBSCRIPTION_ID.",
            "Azure OIDC does not require GitHub Agents or Actions secrets.",
            "Commit these files on a branch and open the described pull request "
            "as a draft; init does not push or open it.",
        ),
    )


def _repository_guard_blockers(discovery) -> tuple[str, ...]:
    blockers: list[str] = []
    if discovery.current_branch != discovery.default_branch:
        blockers.append("Onboarding must run on the default branch.")
    if not discovery.clean:
        blockers.append("Onboarding requires a clean worktree.")
    if not discovery.authenticated_login:
        blockers.append("A locally authenticated GitHub user is required.")
    if discovery.viewer_permission.casefold() != "admin":
        blockers.append("The authenticated GitHub user must have ADMIN permission.")
    return tuple(blockers)


def _write_new_file(
    repository_root: Path,
    path: Path,
    content: str,
) -> OnboardingChange:
    destination = repository_root / path
    destination.parent.mkdir(parents=True, exist_ok=True)
    try:
        with destination.open("x", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
    except FileExistsError:
        return OnboardingChange(
            path=path,
            content=content,
            status=ChangeStatus.CONFLICT,
            detail="Existing file was preserved.",
        )
    return OnboardingChange(
        path=path,
        content=content,
        status=ChangeStatus.CREATED,
    )


def _blocked(
    draft_pr: DraftPullRequest,
    blocker: str,
    changes: tuple[OnboardingChange, ...] = (),
    **values,
) -> OnboardingResult:
    return OnboardingResult(
        status=OnboardingStatus.BLOCKED,
        changes=changes,
        draft_pull_request=draft_pr,
        blockers=(blocker,),
        **values,
    )


def _safe_error(error: Exception) -> str:
    return redact(str(error)) or error.__class__.__name__
