"""Parses the generated GitHub issue-form Markdown into a strict request.

The issue body is untrusted input: it is written by a human (or copied from
one) into a GitHub issue form generated by
:mod:`foundry_opt.onboarding.bundle`. This module never trusts structure,
types, or values found in that body beyond what is explicitly recognized
here, and rejects anything that looks like an attempt to smuggle extra
instructions, secrets, or unknown fields past the strict contracts in
:mod:`foundry_opt.optimization.models`.
"""

from __future__ import annotations

import re
from typing import Any

from pydantic import ValidationError as _PydanticValidationError
import yaml
from yaml.tokens import (
    AliasToken,
    AnchorToken,
    BlockEndToken,
    BlockMappingStartToken,
    BlockSequenceStartToken,
    FlowMappingEndToken,
    FlowMappingStartToken,
    FlowSequenceEndToken,
    FlowSequenceStartToken,
)

from foundry_opt.config.models import MetricPolicy, MutationClass, RepeatPolicy
from foundry_opt.optimization.models import (
    AssetKind,
    DecisionMode,
    DeploymentMode,
    EvaluationAssetRequest,
    OptimizationIssueRequest,
)
from foundry_opt.security import reject_secret_content


_HEADING = re.compile(r"^(#{1,6})[ \t]+(?P<title>\S.*?)[ \t]*$")
_FENCE = re.compile(r"^\s*(`{3,}|~{3,})")
_NO_RESPONSE = "_no response_"
_MAX_YAML_CHARACTERS = 32_768
_MAX_YAML_TOKENS = 4_096
_MAX_YAML_NESTING = 32

TARGET_HEADING = "Configured target"
GOAL_HEADING = "Optimization goal"
DATASETS_HEADING = "Dataset requests"
EVALUATORS_HEADING = "Evaluator requests"
METRICS_HEADING = "Metric policies"
MUTATIONS_HEADING = "Allowed mutations"
CANDIDATE_HEADING = "Candidate decision"
DEPLOYMENT_HEADING = "Deployment decision"

REQUIRED_HEADINGS: tuple[str, ...] = (
    TARGET_HEADING,
    GOAL_HEADING,
    DATASETS_HEADING,
    EVALUATORS_HEADING,
    METRICS_HEADING,
    MUTATIONS_HEADING,
    CANDIDATE_HEADING,
    DEPLOYMENT_HEADING,
)

# The generated issue form always ends with a "Confirmation" checkboxes
# section (see foundry_opt.onboarding.bundle._issue_form). It is the only
# heading tolerated outside of REQUIRED_HEADINGS; anything else, anywhere in
# the body (including before the first or after the last required heading),
# is rejected if it carries non-empty content.
_TOLERATED_HEADINGS = frozenset({"Confirmation"})

_ASSET_FIELDS = frozenset(EvaluationAssetRequest.model_fields)
_METRIC_FIELDS = frozenset(MetricPolicy.model_fields)
_REPEAT_FIELDS = frozenset(RepeatPolicy.model_fields)


class IssueSpecificationError(ValueError):
    """Base class for untrusted issue-form parsing failures."""


class DuplicateSectionError(IssueSpecificationError):
    def __init__(self, heading: str) -> None:
        self.heading = heading
        super().__init__(f"duplicate section heading: {heading!r}")


class MissingSectionError(IssueSpecificationError):
    def __init__(self, headings: tuple[str, ...]) -> None:
        self.headings = headings
        super().__init__(
            "missing required section headings: "
            + ", ".join(repr(heading) for heading in headings)
        )


class UnexpectedSectionError(IssueSpecificationError):
    def __init__(self, heading: str) -> None:
        self.heading = heading
        super().__init__(f"unexpected non-empty section heading: {heading!r}")


class MalformedYamlError(IssueSpecificationError):
    def __init__(self, heading: str, reason: str) -> None:
        self.heading = heading
        super().__init__(f"section {heading!r} is not valid YAML: {reason}")


class UnknownFieldError(IssueSpecificationError):
    def __init__(self, heading: str, fields: tuple[str, ...]) -> None:
        self.heading = heading
        self.fields = fields
        super().__init__(
            f"section {heading!r} has unknown fields: "
            + ", ".join(sorted(fields))
        )


class MismatchedAssetKindError(IssueSpecificationError):
    def __init__(
        self,
        heading: str,
        asset_id: Any,
        expected: str,
        actual: Any,
    ) -> None:
        self.heading = heading
        self.asset_id = asset_id
        super().__init__(
            f"section {heading!r} entry {asset_id!r} declares kind "
            f"{actual!r}, expected {expected!r}"
        )


class SecretContentError(IssueSpecificationError):
    def __init__(self, heading: str, reason: str) -> None:
        self.heading = heading
        super().__init__(
            f"section {heading!r} contains secret-shaped content: {reason}"
        )


def parse_optimization_issue_request(
    *,
    issue_number: int,
    repository: str,
    body: str,
) -> OptimizationIssueRequest:
    """Parses a GitHub issue-form body into a strict ``OptimizationIssueRequest``.

    ``issue_number`` and ``repository`` must come from a verified GitHub
    gateway (never from the issue body itself), so the resulting request can
    never claim an identity the caller did not independently establish.
    """

    _reject_secrets("issue body", body)
    sections = _split_sections(body)
    fields = _validate_structure(sections)

    target = _plain_text(TARGET_HEADING, fields[TARGET_HEADING])
    goal = _plain_text(GOAL_HEADING, fields[GOAL_HEADING])
    datasets = _parse_assets(
        DATASETS_HEADING,
        fields[DATASETS_HEADING],
        AssetKind.DATASET,
    )
    evaluators = _parse_assets(
        EVALUATORS_HEADING,
        fields[EVALUATORS_HEADING],
        AssetKind.EVALUATOR,
    )
    metrics = _parse_metrics(METRICS_HEADING, fields[METRICS_HEADING])
    allowed_mutations = _parse_mutations(
        MUTATIONS_HEADING, fields[MUTATIONS_HEADING]
    )
    decision_mode = _parse_choice(
        CANDIDATE_HEADING, fields[CANDIDATE_HEADING], DecisionMode
    )
    deployment_mode = _parse_choice(
        DEPLOYMENT_HEADING, fields[DEPLOYMENT_HEADING], DeploymentMode
    )

    try:
        return OptimizationIssueRequest(
            issue_number=issue_number,
            repository=repository,
            target=target,
            goal=goal,
            datasets=datasets,
            evaluators=evaluators,
            metrics=metrics,
            allowed_mutations=allowed_mutations,
            decision_mode=decision_mode,
            deployment_mode=deployment_mode,
        )
    except _PydanticValidationError as error:
        raise IssueSpecificationError(
            f"issue specification is invalid: {error}"
        ) from error


def privacy_safe_optimization_issue_body(markdown: str) -> str:
    """Retain only the exact allowlisted issue-form sections."""

    _reject_secrets("issue body", markdown)
    fields = _validate_structure(_split_sections(markdown))
    return (
        "\n\n".join(
            f"### {heading}\n\n{fields[heading]}"
            for heading in REQUIRED_HEADINGS
        )
        + "\n"
    )


# ---------------------------------------------------------------------------
# Markdown structure
# ---------------------------------------------------------------------------


def _split_sections(markdown: str) -> list[tuple[str, str]]:
    lines = markdown.splitlines()
    headings: list[tuple[str, int]] = []
    in_fence = False
    for index, line in enumerate(lines):
        if _FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = _HEADING.match(line)
        if match:
            headings.append((match.group("title").strip(), index))

    sections: list[tuple[str, str]] = []
    for position, (title, start) in enumerate(headings):
        end = (
            headings[position + 1][1]
            if position + 1 < len(headings)
            else len(lines)
        )
        body = "\n".join(lines[start + 1 : end]).strip("\n")
        sections.append((title, body))
    return sections


def _validate_structure(
    sections: list[tuple[str, str]],
) -> dict[str, str]:
    counts: dict[str, int] = {}
    for title, _ in sections:
        counts[title] = counts.get(title, 0) + 1

    duplicated = next(
        (
            heading
            for heading in REQUIRED_HEADINGS
            if counts.get(heading, 0) > 1
        ),
        None,
    )
    if duplicated is not None:
        raise DuplicateSectionError(duplicated)

    missing = tuple(
        heading for heading in REQUIRED_HEADINGS if counts.get(heading, 0) == 0
    )
    if missing:
        raise MissingSectionError(missing)

    # Any unexpected, non-empty heading is rejected regardless of where it
    # appears among the detected sections: before the first required
    # heading, interleaved between required headings, or after the last one.
    # Leading text with no heading at all is never part of `sections` (see
    # `_split_sections`) and therefore remains unaffected.
    for title, body in sections:
        if title in REQUIRED_HEADINGS or title in _TOLERATED_HEADINGS:
            continue
        stripped = body.strip()
        if stripped and stripped.casefold() != _NO_RESPONSE:
            raise UnexpectedSectionError(title)

    return {title: body for title, body in sections if title in REQUIRED_HEADINGS}


# ---------------------------------------------------------------------------
# Field parsing
# ---------------------------------------------------------------------------


def _reject_secrets(heading: str, value: Any) -> Any:
    try:
        return reject_secret_content(value)
    except ValueError as error:
        raise SecretContentError(heading, str(error)) from error


def _plain_text(heading: str, body: str) -> str:
    text = body.strip()
    if not text or text.casefold() == _NO_RESPONSE:
        raise IssueSpecificationError(f"section {heading!r} must not be empty")
    _reject_secrets(heading, text)
    return text


def _load_yaml(heading: str, body: str) -> Any:
    text = body.strip()
    if not text or text.casefold() == _NO_RESPONSE:
        raise IssueSpecificationError(f"section {heading!r} must not be empty")
    if len(text) > _MAX_YAML_CHARACTERS:
        raise MalformedYamlError(
            heading,
            f"content exceeds {_MAX_YAML_CHARACTERS} characters",
        )
    try:
        _validate_yaml_tokens(heading, text)
        value = yaml.safe_load(text)
    except (yaml.YAMLError, RecursionError) as error:
        raise MalformedYamlError(heading, str(error)) from error
    if value is None:
        raise IssueSpecificationError(f"section {heading!r} must not be empty")
    _reject_secrets(heading, value)
    return value


def _validate_yaml_tokens(heading: str, text: str) -> None:
    nesting = 0
    token_count = 0
    starts = (
        BlockMappingStartToken,
        BlockSequenceStartToken,
        FlowMappingStartToken,
        FlowSequenceStartToken,
    )
    ends = (
        BlockEndToken,
        FlowMappingEndToken,
        FlowSequenceEndToken,
    )
    for token in yaml.scan(text):
        token_count += 1
        if token_count > _MAX_YAML_TOKENS:
            raise MalformedYamlError(
                heading,
                f"content exceeds {_MAX_YAML_TOKENS} YAML tokens",
            )
        if isinstance(token, (AnchorToken, AliasToken)):
            raise MalformedYamlError(
                heading,
                "YAML anchors and aliases are not allowed",
            )
        if isinstance(token, starts):
            nesting += 1
            if nesting > _MAX_YAML_NESTING:
                raise MalformedYamlError(
                    heading,
                    f"content exceeds {_MAX_YAML_NESTING} nesting levels",
                )
        elif isinstance(token, ends):
            nesting = max(nesting - 1, 0)


def _build_asset(
    heading: str,
    expected_kind: AssetKind,
    item: Any,
) -> EvaluationAssetRequest:
    if not isinstance(item, dict):
        raise IssueSpecificationError(
            f"section {heading!r} entries must be YAML mappings"
        )
    unknown = set(item) - _ASSET_FIELDS
    if unknown:
        raise UnknownFieldError(heading, tuple(sorted(unknown)))

    payload = dict(item)
    declared_kind = payload.get("kind")
    if declared_kind is not None and declared_kind != expected_kind.value:
        raise MismatchedAssetKindError(
            heading,
            payload.get("asset_id", "<unknown>"),
            expected_kind.value,
            declared_kind,
        )
    payload["kind"] = expected_kind.value

    try:
        return EvaluationAssetRequest(**payload)
    except _PydanticValidationError as error:
        raise IssueSpecificationError(
            f"section {heading!r} entry is invalid: {error}"
        ) from error


def _parse_assets(
    heading: str,
    body: str,
    expected_kind: AssetKind,
) -> tuple[EvaluationAssetRequest, ...]:
    value = _load_yaml(heading, body)
    if not isinstance(value, list) or not value:
        raise IssueSpecificationError(
            f"section {heading!r} must be a non-empty YAML list"
        )
    return tuple(_build_asset(heading, expected_kind, item) for item in value)


def _parse_metrics(heading: str, body: str) -> dict[str, MetricPolicy]:
    value = _load_yaml(heading, body)
    if not isinstance(value, dict) or not value:
        raise IssueSpecificationError(
            f"section {heading!r} must be a non-empty YAML mapping"
        )
    metrics: dict[str, MetricPolicy] = {}
    for name, fields in value.items():
        if not isinstance(name, str) or not isinstance(fields, dict):
            raise IssueSpecificationError(
                f"section {heading!r} entries must map metric names to "
                "mappings"
            )
        unknown = set(fields) - _METRIC_FIELDS
        if unknown:
            raise UnknownFieldError(heading, tuple(sorted(unknown)))
        repeat = fields.get("repeat")
        if isinstance(repeat, dict):
            unknown_repeat = set(repeat) - _REPEAT_FIELDS
            if unknown_repeat:
                raise UnknownFieldError(heading, tuple(sorted(unknown_repeat)))
        try:
            metrics[name] = MetricPolicy(**fields)
        except _PydanticValidationError as error:
            raise IssueSpecificationError(
                f"section {heading!r} metric {name!r} is invalid: {error}"
            ) from error
    return metrics


def _parse_mutations(heading: str, body: str) -> frozenset[MutationClass]:
    value = _load_yaml(heading, body)
    if not isinstance(value, list) or not value:
        raise IssueSpecificationError(
            f"section {heading!r} must be a non-empty YAML list"
        )
    mutations: list[MutationClass] = []
    for entry in value:
        if not isinstance(entry, str):
            raise IssueSpecificationError(
                f"section {heading!r} entries must be strings"
            )
        try:
            mutations.append(MutationClass(entry))
        except ValueError as error:
            raise IssueSpecificationError(
                f"section {heading!r} has an unknown mutation class "
                f"{entry!r}"
            ) from error
    return frozenset(mutations)


def _parse_choice(heading: str, body: str, enum_cls: type) -> Any:
    text = _plain_text(heading, body)
    try:
        return enum_cls(text)
    except ValueError as error:
        raise IssueSpecificationError(
            f"section {heading!r} has an unknown value {text!r}"
        ) from error
